spring:
  application:
    name: ecommerce-api
  
  # H2 Database Configuration (for development)
  datasource:
    url: jdbc:h2:mem:ecommerce
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT Configuration
jwt:
  secret: mySecretKey
  expiration: 86400000 # 24 hours

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.example.ecommerce: DEBUG
    org.springframework.security: DEBUG

---
# Production Profile (MySQL)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false